# config.yaml
version: 3
endpoint: http://localhost:8081
admin_secret: 3lKK6v5dGIe6EqmrA2UXWxuSCO4prhgasehH0spIJOJojxYdDGW0sVg5hCU4EoBf

metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
