# config.yaml
version: 3
endpoint: http://localhost:8081
admin_secret: ${NEXT_PUBLIC_HASURA_GRAPHQL_ADMIN_SECRET}

metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
