# docker-compose.prod.yml
version: "3.8"

services:
  # ▼ Next.js コンテナ（本番用）
  nextjs:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      hasura:
        condition: service_healthy
      libretranslate:
        condition: service_started

  # ▼ Hasura コンテナ（Supabase Cloudに接続）
  hasura:
    image: hasura/graphql-engine:v2.46.0
    platform: linux/arm64
    ports:
      - "8081:8081"
    env_file:
      - .env.production
    environment:
      # 本番環境では Supabase Cloud の接続URLを環境変数で指定
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${NEXT_PUBLIC_HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"wbmvACz5zBHLgMFowQDj4OaTtNAt9EplKs1fyQi6qgPIP4eFoX31+OBWKfUAXYGBmcDCYyMDfQ7Zi5rjj4TOdw=="}'
      HASURA_GRAPHQL_SERVER_PORT: "8081"
      HASURA_GRAPHQL_SERVER_HOST: "0.0.0.0"
      HASURA_GRAPHQL_ENABLED_APIS: "metadata,graphql,pgdump,config"
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
    # 本番環境では supabase サービスは起動しないので depends_on の指定を削除
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    entrypoint: >
      sh -c "echo 'Using Supabase Cloud...';
      graphql-engine serve"

  # ▼ 本番でもLibreTranslateをローカルコンテナで動かす場合
  libretranslate:
    image: libretranslate/libretranslate:latest
    platform: linux/arm64
    ports:
      - "8000:5000"
    env_file:
      - .env.production
    environment:
      LT_DEBUG: "true"
      LT_PORT: "5000"
    command: ["--load-only", "en,id,ja,fr,de,zh"]
