# docker-compose.dev.yml
services:
  nextjs:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env.development
    volumes:
      - ./jwt-secret.json:/jwt-secret.json:ro
    depends_on:
      hasura:
        condition: service_healthy
      libretranslate:
        condition: service_started

  # ▼ Hasura コンテナ（ローカルSupabaseに接続）
  hasura:
    image: hasura/graphql-engine:v2.46.0
    platform: linux/arm64
    ports:
      - "8081:8081"
    env_file:
      - ./.env.development
    depends_on:
      supabase:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    entrypoint: >
      sh -c "until nc -z supabase 5432; do echo 'Waiting for Supabase...'; sleep 2; done;
      graphql-engine serve"
    volumes:
      - ./jwt-secret.json:/jwt-secret.json:ro

  # ▼ ローカル開発用 Supabase (PostgreSQL + PostGIS)
  supabase:
    image: imresamu/postgis-arm64:16-3.4
    platform: linux/arm64
    ports:
      - "54330:5432"
    env_file:
      - ./.env.development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sppa"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  # ▼ LibreTranslate（翻訳API）
  libretranslate:
    image: libretranslate/libretranslate:latest
    platform: linux/arm64
    ports:
      - "8000:5000"
    env_file:
      - ./.env.development
    command: ["--load-only", "en,id,ja,fr,de,zh"]