# config/docker-compose.dev.yml
services:
  # ▼ Next.js コンテナ（開発用）
  nextjs:
    build:
      context: ../
    ports:
      - "3000:3000"
    env_file:
      - /Users/tanitomohiro/github/sppa/.env.development
    depends_on:
      hasura:
        condition: service_healthy
      libretranslate:
        condition: service_started

  # ▼ Hasura コンテナ（ローカルSupabaseに接続）
  hasura:
    image: hasura/graphql-engine:v2.46.0
    platform: linux/arm64
    ports:
      - "8081:8081"
    env_file:
      - /Users/tanitomohiro/github/sppa/.env.development
    environment:
      # Docker内の接続先は.env.developmentで指定された値を利用
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_SERVER_PORT: "8081"
      HASURA_GRAPHQL_SERVER_HOST: "0.0.0.0"
      HASURA_GRAPHQL_ENABLED_APIS: "metadata,graphql,pgdump,config"
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
    depends_on:
      supabase:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    entrypoint: >
      sh -c "until nc -z supabase 5432; do echo 'Waiting for Supabase...'; sleep 2; done;
      graphql-engine serve"

  # ▼ ローカル開発用 Supabase (PostgreSQL + PostGIS)
  supabase:
    image: imresamu/postgis-arm64:16-3.4
    platform: linux/arm64
    ports:
      - "54330:5432"
    env_file:
      - /Users/tanitomohiro/github/sppa/.env.development
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sppa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sppa"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  # ▼ LibreTranslate（翻訳API）
  libretranslate:
    image: libretranslate/libretranslate:latest
    platform: linux/arm64
    ports:
      - "8000:5000"
    env_file:
      - ../.env.development
    environment:
      LT_DEBUG: "true"
      LT_PORT: "5000"
    command: ["--load-only", "en,id,ja,fr,de,zh"]
