# hasura/config.yaml
version: 3
endpoint: http://localhost:8081
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000

databases:
  - name: sppa
    url:
      from_env: HASURA_GRAPHQL_DATABASE_URL
